### PR TITLE
Switch to textshaping

### PR DESCRIPTION
**Pull request by teunbrand**
Obviously not as fancy as the textshaping package, but as a first step towards a fix of #31.

``` r
library(geomtextpath)
#> Loading required package: ggplot2
#> Warning: package 'ggplot2' was built under R version 4.1.1

ggplot(iris, aes(x=Sepal.Length))+
  geom_textpath(aes(label="Composed: \u00ea, DeC: e\u0302, \u05d0\u05aa\u05aa"), stat="density", vjust=-0.2, size=8, fontface=1)+
  ylim(0.1,0.5)
#> Warning: Removed 83 rows containing missing values (geom_textpath).
```

<sup>Created on 2021-12-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Can't currently handle the Hangul syllable gag composition, but neither does the reprex' graphics device (ragg displays the geom_text correctly and geom_textpath as shown below).

``` r
library(geomtextpath)
#> Loading required package: ggplot2
#> Warning: package 'ggplot2' was built under R version 4.1.1
ggplot(data.frame(x = c(1, 2), y = 1), aes(x, y)) +
  geom_text(label = "\u1100\u1161\u11a8", size = 10, colour = "blue", 
            family = "Noto Sans KR") +
  geom_textpath(label = "\u1100\u1161\u11a8", size = 10, include_line = FALSE,
                family = "Noto Sans KR")
#> Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, :
#> font family not found in Windows font database
```

<sup>Created on 2021-12-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Test now only works on windows, I'd have to figure out later why they fail on ubuntu/macOS, hence I'm marking this as a draft.

### CODE REVIEW

**Comment by AllanCameron** [comment]
Looks good Teun. Are you happy for me to merge this now?

**Comment by teunbrand** [comment]
Almost! there is a small merge conflict I'll resolve

**Comment by teunbrand** [comment]
Strange, it seems the check fails because one package cannot be installed, which isn't within our control. It was passing all checks moments ago on my own repo. Anyway, I'm guessing this is good to merge now?

**Comment by AllanCameron** [comment]
At last! Just needed roxygenized again after the description tweaks

**Comment by teunbrand** [comment]
Thanks for fixing the error Allan!

**Pull request merged**
