### PR TITLE
Refactor `.get_path_points()` part II

### PR DESCRIPTION
**Pull request by teunbrand**
Hi Allan,

In brief:

- I also refactored the anchor point calculation. Unfortunately, it clashed with your refactoring of the same code. The main difference is that you applied the anchors directly to the text, whereas mine just calculated the anchor points (for ease of testing). In this PR, I've chosen to keep my version, because:
- I've written unit tests for the anchor point calculation. I think testing the calculation separately from the application to the text is easier.
- I've also captured the 'project text to curve'-step in a separate function.
- Calculation of the offset vector and the glyph membership to that offset is now responsibility of `measure_text()`.

I'm not saying we should keep my refactoring of the `hadjust` parameter over yours, I can go back and revert yours if you like that better.

### CODE REVIEW

**Comment by teunbrand** [comment]
I've converted this PR to a draft because I've spotted a bug in the meantime that I intend to fix

**Comment by teunbrand** [comment]
Nevermind, it was not a bug with my code. It seems our text is slightly wider than the default `geom_text()` (irrespective of this PR):

``` r
library(geomtextpath)
#> Loading required package: ggplot2
df <- data.frame(x = c(1, 1000), y = 1, text = "This is a perfectly flat label")

p <- ggplot(df, aes(x, y, label = text)) +
    geom_textpath(size = 6, hjust = 0) +
    geom_text(data = transform(df[1,], y = 1.02), 
              hjust = 0, size = 6, colour = "blue") +
    ylim(c(0.9, 1.1))
p
```



<sup>Created on 2021-11-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by AllanCameron** [comment]
That's weird. Mine isn't like that. I've pulled and confirmed that my local version is up to date with the main repo, cleaned and rebuilt, then run your code. I get this:
``` r
library(geomtextpath) # Current main branch of your repo
#> Loading required package: ggplot2
df <- data.frame(x = c(1, 1000), y = 1, text = "This is a perfectly flat label")

p <- ggplot(df, aes(x, y, label = text)) +
    geom_textpath(size = 6, hjust = 0) +
    geom_text(data = transform(df[1,], y = 1.02), 
              hjust = 0, size = 6, colour = "blue") +
    ylim(c(0.9, 1.1))
p
```
image

The image you posted seems to show an increase in the letter spacing in the textpath compared to mine.

**Comment by AllanCameron** [comment]
I'll merge your changes and run it again

**Comment by teunbrand** [comment]
Hmm that is strange indeed. I build the reprex on a different machine than my own with a fresh clone of the repo, so that I was sure I wasn't running this PR's code. Could be a OS specific thing maybe? The reprex was from a linux machine.

**Comment by AllanCameron** [comment]
No, I still don't see the results you are getting. I have merged, pulled your changes and reinstalled. I have tried it on two different PCs, though both run Windows 10.

Same code again produces this:

image

It could be OS specific. Or maybe try reloading RStudio?

**Comment by teunbrand** [comment]
Strange, probably an OS thing. The effect on windows is *much* milder than on linux. Both the files below were created using `ggsave(plot =  p, width = 7, height = 5, filename = "test_plot.pdf")`.

[linux_R4.05.pdf](https://github.com/AllanCameron/geomtextpath/files/7611981/linux_R4.05.pdf)
[windows10_R4.1.pdf](https://github.com/AllanCameron/geomtextpath/files/7611983/windows10_R4.1.pdf)

**Comment by AllanCameron** [comment]
Yes, there _is_ a slight difference on Windows machines, One thought that occurs is that the output of `shape_string` is in pixels, and we are therefore rounding to the nearest pixel when measuring widths, etc. This could lead to inconsistent spacing when the text is stretched. For example, if we assume that a point size of 100 gives a very accurate pixel representation of its underlying vector outlines, then the x offsets of 100-point text should be very accurate too:
``` r
library(systemfonts)
#> Warning: package 'systemfonts' was built under R version 4.1.1

str <- "Test widths"

size_100 <- shape_string(str, size = 100)$shape$x_offset
size_50  <- shape_string(str, size =  50)$shape$x_offset
size_10  <- shape_string(str, size =  10)$shape$x_offset
size_5   <- shape_string(str, size =   5)$shape$x_offset

size_100
#>  [1]   0  50 106 156 184 212 284 306 362 390 446
```
If we scale the size 50 font by 2, we should get the same output:
``` r
size_50 * 2
#>  [1]   0  50 106 156 184 212 284 306 362 390 446
```
However, by the time the font size gets down to size 10, the fine details are starting to get lost:
``` r
size_10 * 10
#>  [1]   0  60 120 170 200 230 300 320 380 410 470
```
And this is even worse at a point size of 5:
``` r
size_5 * 20
#>  [1]   0  60 120 180 200 220 300 320 380 400 460
```
It does make me wonder whether we should use a large value of "size" for `shape_string` and shrink the results. I think that might give better accuracy.
<sup>Created on 2021-11-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>


``` r

**Comment by AllanCameron** [comment]
Yes, that seems to have improved the Windows version. Still not perfect though:
``` r
library(geomtextpath) # Current main branch of your repo
#> Loading required package: ggplot2
df <- data.frame(x = c(1, 1000), y = 1, text = "This is a perfectly flat label")

p <- ggplot(df, aes(x, y, label = text)) +
    geom_textpath(size = 6, hjust = 0) +
    geom_text(data = transform(df[1,], y = 1.02), 
              hjust = 0, size = 6, colour = "blue") +
    ylim(c(0.9, 1.1))

ggsave(plot = p, width = 7, height = 5, filename = "test_plot.pdf")
```

[test_plot.pdf](https://github.com/AllanCameron/geomtextpath/files/7612057/test_plot.pdf)

**Comment by teunbrand** [comment]
I'm working on `measure_text()` right now for an unrelated thing, I'll incorporate 'upscaling' the size in the next PR.

**Comment by AllanCameron** [comment]
Good stuff. Does it make any difference to the appearance on your machines?

**Comment by teunbrand** [comment]
Yes, yes it does :) Looks the same on linux as on windows now.

**Pull request merged**
