### PR TITLE
Expand vignettes

### PR DESCRIPTION
**Pull request by teunbrand**
Hi Alan,

This PR expands the vignettes a bit and fixes a few random bugs I caught while coming up with examples. 
Of note, when I ran this through `devtools::check(document = FALSE, args = c('--as-cran'))`, I got the following note:

> checking installed package size ... NOTE
    installed size is  5.5Mb
    sub-directories of 1Mb or more:
      doc    2.5Mb
      help   2.0Mb
      
I don't think this is a problem *yet*, but we might start thinking about ways to compress PNGs, as the copious examples might cause the package size to exceed CRAN's limits.

### CODE REVIEW

**Comment by AllanCameron** [comment]
I thought 5MB was the limit for CRAN? I dropped the resolution of the readme images a while back the last time I got this note.

**Comment by teunbrand** [comment]
Yeah 5Mb is the limit, but I have no clue where to find the 'help' folder to inspect what might be causing large files. The doc folder is indeed a bit bloated due to pngs in the vignettes. However, as far as I can tell, the PNGs are already rendered at screen resolution (72 dpi), so it might start to look worse if we manually set this lower.

**Comment by AllanCameron** [comment]
The help folder is in your R library:
```r
paste0(.libPaths()[1], "/geomtextpath/help")
```

**Comment by AllanCameron** [comment]
By the way, I love the updated aesthetics vignette.

**Pull request merged**
