### PR TITLE
Tests and safety

### PR DESCRIPTION
**Pull request by teunbrand**
In brief, this small PR:

* Adds tests for the trigonometry helpers.
* Deduplicates subsequent (near)-identical points from paths, which caused some unstable estimates of the angles and arclengths.
* I've reintroduced `.stretch_by_one()` because it was used by `.get_curvature()`. I don't know if we need `.get_curvature()`, but it seemed sensible to have both the functions or neither of them and I'm defaulting to the former (though I have no strong feelings, so feel free to choose the other option).

### CODE REVIEW

**Comment by AllanCameron** [comment]
Great, thanks Teun.

I purposefully held on to `.get_curvature`, because I have a feeling we will need it later - we can always get rid of it if we don't.

Even though I'm confident that the bisector method places the text correctly, I think the overall appearance of text still looks a little crowded on the concave side of a curve, and too stretched on the convex side (see the "setosa" over the bump on the vertically faceted plot in the readme). This is probably because the text is always spaced correctly at the baseline, but the tops of the letters will naturally diverge or converge according to the curve the letters form, A curvature calculation may help compensate for this, though perhaps the best alternative would be to calculate spacing based on the midpoint of the text. I will explore this option next. I'm also trying to get my head round hjust at the moment.

I'm keen to get the whole mechanism of the textGrob as robust, efficient and understandable as possible so that we can use it without worries on other geoms and coords. I think we're getting close, and have achieved a lot in the last two weeks!

**Comment by AllanCameron** [comment]
Actually, it looks as though the problem I describe is caused by the vjust of the textGrob being fixed at 0. It goes away when the vjust passed to textGrob is fixed at 0.5, but this messes up the position of text relative to the line.

**Comment by teunbrand** [comment]
Does it help then to subtract 0.5 vjust in `measure_text()`? I'm a bit stuck on the `halign` part of things, I can't seem to figure out the exact formula to do it correctly.

**Comment by AllanCameron** [comment]
That's a good idea. It _almost_ works, but gives the wrong vjust result with multi-line text. I'll keep working on it. I had a crack at hjust today, and almost managed it, but when I get "left" to work, "right" didn't work.

**Comment by AllanCameron** [comment]
Aha! Fixed the vjust problem. Simply get the ymin value for a random letter "x" with a vjust of 0.5. We can subtract that from `letters$ymin`.

**Comment by teunbrand** [comment]
Well that is an appropriately chosen letter to measure the height of https://en.wikipedia.org/wiki/X-height

**Comment by AllanCameron** [comment]
I think the latest commit fixes the halign (apologies for the long reprex)
``` r
library(geomtextpath)
#> Loading required package: ggplot2

df <- data.frame( x = seq(0, 2, length = 200),
                  y = -(seq(0, 2, length = 200)^2),
                  label = paste("Life’s but a walking shadow,",
                                "a poor player, that struts and",
                                "frets his hour upon the stage, ",
                                "and then is heard no more;",
                                "it is a tale told by an idiot,",
                                "full of sound and fury,","signifying nothing",
                                sep = "\n"))

p <- ggplot(df, aes(x, y, label = label)) + 
  coord_cartesian(xlim = c(0, 3)) + 
  scale_x_continuous(limits = c(-4, 4)) + 
  scale_y_continuous(limits = c(-4, 5)) +
  theme(aspect.ratio = 1)

p +
  geom_textpath(size = 3, linetype = 1, vjust = 0, hjust = 0,
                halign = "left", cut_path = FALSE, lineheight = 1) 
```



``` r
p +
  geom_textpath(size = 3, linetype = 1, vjust = 0, hjust = 0.5,
                halign = "left", cut_path = FALSE, lineheight = 1) 
```



``` r
p +
  geom_textpath(size = 3, linetype = 1, vjust = 0, hjust = 1,
                halign = "left", cut_path = FALSE, lineheight = 1) 
```



``` r
p +
  geom_textpath(size = 3, linetype = 1, vjust = 0, hjust = 0,
                halign = "center", cut_path = FALSE, lineheight = 1) 
```



``` r
p +
  geom_textpath(size = 3, linetype = 1, vjust = 0, hjust = 0.5,
                halign = "center", cut_path = FALSE, lineheight = 1) 
```



``` r
p +
  geom_textpath(size = 3, linetype = 1, vjust = 0, hjust = 1,
                halign = "center", cut_path = FALSE, lineheight = 1) 
```



``` r
p +
  geom_textpath(size = 3, linetype = 1, vjust = 0, hjust = 0,
                halign = "right", cut_path = FALSE, lineheight = 1) 
```



``` r
p +
  geom_textpath(size = 3, linetype = 1, vjust = 0, hjust = 0.5,
                halign = "right", cut_path = FALSE, lineheight = 1) 
```



``` r
p +
  geom_textpath(size = 3, linetype = 1, vjust = 0, hjust = 1,
                halign = "right", cut_path = FALSE, lineheight = 1) 
```



<sup>Created on 2021-11-26 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by AllanCameron** [comment]
As a bit of fun - check this out.

``` r
library(gganimate)
library(geomtextpath)

p <- ggplot(within(rbind(iris, iris), hjust <- rep(0:1, each = 150)), 
            aes(x = Sepal.Length, color = Species, hjust = hjust, vjust = 0)) + 
     geom_textpath(aes(label = Species), stat = "density", size = 8)

p

anim <- p + 
  transition_states(hjust,
                    transition_length = 10,
                    state_length = 1)

myanim <- animate(anim, fps = 50, duration = 10)

save_animation(myanim, "iris.gif")
```

**iris.gif**

iris

**Comment by teunbrand** [comment]
That is definitely awesome! Text rollercoaster! Also good work on the `halign` parameter it works much better than before. Unfortunately I was refactoring the same thing as you were a few hours ago, so now I have to resolve a merge conflict :D

**Comment by AllanCameron** [comment]
For comparison, here's the text rollercoster after the improvements in letter spacing accuracy. There should be a bit less flickering of the letter positions within the words. If there is, it's pretty subtle.

iris

**Pull request merged**
