### PR TITLE
`geom_richtextpath()`

### PR DESCRIPTION
**Pull request by teunbrand**
Hi Allan,

As discussed in #39, here is the first iteration of `geom_richtextpath()`. A few notes:

* It currently supports the same tags as {gridtext}, with the exception of images. I just felt it was out of scope to curve images along a path.
* Functions borrowed from {gridtext} are isolated in `borrowed_gridtext.R` just to make it clear what we've borrowed and there are no mixed copyright files besides this one.
* The inferface to these borrowed functions are in the `parse_richtext()`, which interprets the html text (markdown gets converted to html beforehand).
* After text is parsed, it gets measured with `measure_richtext()`, which keeps track of substrings and does the offsetting for sub- and superscripts. 
* After the measurement, it pretty much just works with regular `makeContent.textpath()`, so I didn't need to implement a new method. A few lines of code have been adjusted in `place_text()` and `.add_text_grob()`, nothing mayor, just tracking a `substring` variable instead of an `id` when appropriate.
* There was also a bug with multi-line text have the order of the lines reversed when they were flipped, which I've fixed. I came across this trying do deal with sub- and superscripts.

``` r
library(geomtextpath)
#> Loading required package: ggplot2
#> Warning: package 'ggplot2' was built under R version 4.1.1

label <- paste0(
  "Indometacin (",
  "C<sub>19</sub>H<sub>16</sub>",
  "<span style='color:limegreen'>Cl</span>",
  "<span style='color:blue'>N</span>",
  "<span style='color:red'>O</span><sub>4</sub>",
  ") concentration"
)

ggplot(Indometh, aes(time, conc)) +
  geom_point() +
  geom_richtextpath(
    label = label,
    stat = "smooth", formula = y ~ x, method = "loess",
    vjust = -3, size = 8
  ) +
  scale_x_log10()
```

<sup>Created on 2021-12-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

There are a few things that could still be done better:
* I don't think the way we're handling nested sub- and superscripts is the best, we might be offsetting the text too much.
* There is no option yet to handle straight labels, which I'll get around to at some point.

### CODE REVIEW

**Comment by teunbrand** [comment]
Hmm a few things didn't work out on R-devel. Might download the devel version later and check out what is up with this.

**Comment by AllanCameron** [comment]
Nice work Teun!

I have a couple of questions:
 1) Do we need a separate richtextpathGrob, or could the functionality be moved into textpathGrob?
 2) If this is not possible, is it at least better to optionally dispatch richtextpathGrob from inside the `GeomTextpath`layer so that its functionality is propagated throughout the other geoms? We surely don't want to have another set of geoms.
 3) Shouldn't we just replace textpathGrob with richtextpathGrob? It seems to me that the functionality of the textpathGrob is just a subset of the richtextpathGrob, so why not just make richtextpathGrob the textpathGrob?

**Comment by teunbrand** [comment]
Yes, good questions that mostly slipped my mind as I was focussed on getting it to work in the first place!

> Do we need a separate richtextpathGrob, or could the functionality be moved into textpathGrob?

I think it can, but it would be easier to substitute current `textpathGrob()` with the `richtextpathGrob()` from this PR with an additional parameter `rich = TRUE/FALSE`. The rich variant does al the things the plain variant does, but I'd have to substitute and check if any tests fail. The only thing preventing this at the moment is that I haven't gotten around to doing the `straight = TRUE` for rich text yet (the rich-variant of `measure_exp()` specifically). Partially this is because (as far as I can tell) parsed plotmath expressions and rich-text are mutually exclusive.

> We surely don't want to have another set of geoms.

100% agree and I think the the suggestion to move rich text functionality to `textpathGrob()` is a good one.

**Comment by AllanCameron** [comment]
Are you happy for me to merge now Teun?

**Comment by teunbrand** [comment]
Yes this seems fine for now, I'll work on merging this with `textpathGrob()` later

**Pull request merged**
