### PR TITLE
Start vignettes

### PR DESCRIPTION
**Pull request by teunbrand**
Hi Allan,

In brief, this PR does the following:

* I've started with an 'introduction' vignette, but isn't substantial yet.
* I've created an 'aesthetics' vignette, describing what `hjust`, `vjust`, `halign` and `spacing` do.
* It adds a `linecolour` aesthetic, that can be separate from, but defaults to, the text colour. I'm not sure the implementation is the most elegant, but it seems to work.

### CODE REVIEW

**Comment by AllanCameron** [comment]
Something I wondered about before getting too far into a vignette, is whether we have correctly named the `hjust` and `halign` parameters. Remember, we can easily make `halign` numeric, which would essentially turn it into an actual `hjust`, analagous to the `hjust` in `geom_text`. What we currently call `hjust` might be better called `text_at` or similar.

Also, I don't think `vjust` and `hjust` are properly mapped to scales at the moment. You can map to `hjust` as long as you do it numerically, but if you try to pass a string or factor it fails. Presumably this needs taken care of in the `setup_data` member of the geom.

**Comment by teunbrand** [comment]
The `vjust` and `hjust` aesthetics can be mapped to scales, there just aren't any scales for them, so you'd have to make a scale. Simultaneously demonstrating that `vjust` can vary across groups:

``` r
library(geomtextpath)
#> Loading required package: ggplot2
#> Warning: package 'ggplot2' was built under R version 4.1.1

df <- data.frame(
  x = c(1, 1.5, 2, 2.5, 3, 3.5), y = 1,
  lab = rep(c("First", "Second", "Third"), each = 2)
)


p <- ggplot(df, aes(x, y, label = lab)) +
  geom_textpath(aes(vjust = c(0.5, 0.5, 1, 1, 0, 0)))

p
```



``` r
p + continuous_scale("vjust", "vjust_scale", scales::rescale_pal(c(-1, 2)),
                     guide = "none")
```



<sup>Created on 2021-11-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I think the `hjust` and `halign` parameters are correctly named and conceptually consistent with how gridtext/ggtext use the terms.  Consider the case where are path becomes very small, so it becomes like a point-anchor. It still behaves consistently with `geom_text`'s `hjust` parameter:

``` r
library(geomtextpath)
#> Loading required package: ggplot2
#> Warning: package 'ggplot2' was built under R version 4.1.1

df <- data.frame(
  x = c(1, 1.5, 2, 2.5, 3, 3.5), y = 1,
  lab = rep(c("First", "Second", "Third"), each = 2)
)

small_nr <- 1001 * .Machine$double.eps
df_textpath <- data.frame(
  x = c(1, 1 + small_nr, 2, 2 + small_nr, 3, 3 + small_nr), y = 1,
  lab = rep(c("First", "Second", "Third"), each = 2),
  hjust = rep(c(0,0.5,1), each = 2)
)

df_text <- data.frame(
  x = 1:3, y = 1.1,
  lab = c("First", "Second", "Third"),
  hjust = c(0, 0.5, 1)
)

ggplot(mapping = aes(x = x, y = y, label = lab, hjust = hjust)) +
  geom_text(data = df_text, colour = "blue") +
  geom_textpath(data = df_textpath, colour = "red") +
  lims(x = c(0.8, 3.2), y = c(0.9, 1.2))
```



<sup>Created on 2021-11-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by teunbrand** [comment]
Also to demonstrate that you can pass a string as `hjust` parameter just fine, as long as you attach a discrete scale that takes care of the string-value mapping:

``` r
library(geomtextpath)
#> Loading required package: ggplot2
#> Warning: package 'ggplot2' was built under R version 4.1.1

df <- data.frame(
  x = c(1, 1.5, 2, 2.5, 3, 3.5), y = 1,
  lab = rep(c("First", "Second", "Third"), each = 2)
)

# Group is inferred from label in this case
p <- ggplot(df, aes(x, y, label = lab)) +
  geom_textpath(aes(hjust = lab)) +
  lims(x = c(0.5, 4))

# Hijacking manual colour scale because ggplot2:::manual_scale isn't exported
p + scale_colour_manual(
  aesthetics = "hjust",
  values = c(-1, 0.5, 2)
)
```



<sup>Created on 2021-11-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by AllanCameron** [comment]
Very nice demo Teun. These all look fairly trivial to implement.

**Comment by teunbrand** [comment]
Yeah we could add some scales as convenience, but I don't know if we should bother (since ggplot2 hasn't either). If you're on the chaotic/evil side of the DnD alignment chart, you can even implement a label scale.

``` r
library(geomtextpath)
#> Loading required package: ggplot2
#> Warning: package 'ggplot2' was built under R version 4.1.1

df <- data.frame(
  x = c(1, 1.5, 2, 2.5, 3, 3.5), y = 1,
  lab = rep(c("First", "Second", "Third"), each = 2)
)

# Group is inferred from label in this case
p <- ggplot(df, aes(x, y, label = lab)) +
  geom_textpath() +
  lims(x = c(0.5, 4))

# Hijacking manual colour scale because ggplot2:::manual_scale isn't exported
p + scale_colour_manual(
  aesthetics = "label",
  values = c("These are", "not the labels", "you're looking for"),
  guide = "none"
)
```



<sup>Created on 2021-11-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by AllanCameron** [comment]
You must make a wicked DM Tuen.

I like the aesthetics vignette. I see that my warning gets triggered where the text starts to get ugly at the center of the spiral, once the curvature exceeds the offset. I think this is quite appropriate here though. We can decide to drop the warning if we want, but at least we know we have a flag to pick up problems and potentially address them by alternative means.

**Pull request merged**
