### PR TITLE
Simplify and text justification

### PR DESCRIPTION
**Pull request by teunbrand**
Hi Allan,

Here is my attempt at simplifying the code, primarily in terms of parameters being passed around.

In brief:
* All text shaping in terms of line breaks and calculating offset distances is now ruled by the `shape_string()` function.
* This reduced the need for passing variants of `vjust`s around and regrouping by linebreaks.
* The code is not entirely clean yet, I still have to figure out what I can safely detach and what I cannot. It was hard to figure out as there aren't too many unit tests yet that will inform you when you've done something wrong. I also still need to document some stuff here and there.
* There is now a `halign` parameter to the geom. It sort of works when the `hjust` coincides, but it still needs some work. 

I know you worked hard getting the linebreaks and vjusts just right and it is pretty amazing stuff. This PR makes some of that work obsolete and I feel a bit bad about doing that to your work.

``` r
library(patchwork)
library(ggplot2)
#> Warning: package 'ggplot2' was built under R version 4.1.1
library(geomtextpath)

df <- data.frame( x = seq(0, 2, length = 200),
                  y = -(seq(0, 2, length = 200)^2),
                  label = paste("Life’s but a walking shadow,",
                                "a poor player, that struts and",
                                "frets his hour upon the stage, ",
                                "and then is heard no more;",
                                "it is a tale told by an idiot,",
                                "full of sound and fury,","signifying nothing",
                                sep = "\n"))

p <- ggplot(df, aes(x, y, label = label)) + 
  coord_cartesian(xlim = c(0, 3)) + 
  scale_x_continuous(limits = c(-4, 4)) + 
  scale_y_continuous(limits = c(-4, 5)) +
  theme(aspect.ratio = 1)

p1 <- p +
  geom_textpath(size = 3, linetype = 1, vjust = 0, hjust = 0.5,
                halign = "center", cut_path = FALSE, lineheight = 1) +
  ggtitle("hjust = 0.5,\nhalign = 'center'")
p2 <- p +
  geom_textpath(size = 3, linetype = 1, vjust = 0, hjust = 0,
                halign = "left", cut_path = FALSE, lineheight = 1) +
  ggtitle("hjust = 0,\nhalign = 'left'")

p3 <- p +
  geom_textpath(size = 3, linetype = 1, vjust = 0, hjust = 1,
                halign = "right", cut_path = FALSE, lineheight = 1) +
  ggtitle("hjust = 1,\nhalign = 'right'")

p1 + p2 + p3 + plot_layout(heights = 0.5)
```

<sup>Created on 2021-11-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

### CODE REVIEW

**Comment by AllanCameron** [comment]
Hi Teun. This looks great. I'm having some problems merging but will fix this after after a good night's sleep. I have been working today on a much better curvature calculation that should help with the flow of text - perhaps that led to some of the merge conflicts. I should have time to have a good look at this tomorrow

**Comment by teunbrand** [comment]
Hi Allan, I'm sorry about the merging stuff, the CI gave me green check marks after I had integrated the changes up to a few hours before so I (perhaps erroneously) assumed it was good to go. Thanks for fixing the merge!

**Comment by AllanCameron** [comment]
No worries Teun - I probably did something stupid to screw up the merge.

I've had a bit of time to try to understand your changes. I often find that trying to refactor a longer function into shorter functions allows me to understand what's going on better, so I have done this with your `calc_offset` function. This also allowed me to re-use some of the trig helpers, and thereby reduce replication. 

I like the way you use arrays and lists to pass the distance information around, and I think moving in this direction will allow more consistent results and is easier to maintain. You really don't need to worry about making the work I did obsolete; I enjoy seeing other ways of doing things, and as you have said yourself, this is about having fun and learning. An improvement in the code will never upset me!

I'm struggling a little bit to follow the calculation of the offset points on the bisectors. It seems to work, but I don't really understand why it does. Is this a formula you worked out yourself, or is there a reference you used that I can read?

My next target will be trying to refactor `.get_path_points`. Ultimately it would be nice to have these large co-ordinating functions short enough to have in the `textpathGrob` file, with most of the actual data manipulations left to the trig helpers. Having trig helpers short, simple, clearly named and modular will help us keep track of the manipulations.

**Comment by teunbrand** [comment]
I can't really explain it terms of math (I'm bad at formal math, but have some intuition about numbers), later today I'll draw a picture illustrating the concept once I'm back from work!

**Comment by AllanCameron** [comment]
One issue I've discovered on my machine which doesn't appear to affect you is that I'm getting artefacts because the grob is printing newline characters as the null character (an empty square):
``` r
df <- data.frame( x = seq(0, 2, length = 200),
                  y = -(seq(0, 2, length = 200)^2),
                  label = paste("Life’s but a walking shadow,",
                                "a poor player, that struts and",
                                "frets his hour upon the stage, ",
                                "and then is heard no more;",
                                "it is a tale told by an idiot,",
                                "full of sound and fury,","signifying nothing",
                                sep = "\n"))

p <- ggplot(df, aes(x, y, label = label)) + 
  coord_cartesian(xlim = c(0, 3)) + 
  scale_x_continuous(limits = c(-4, 4)) + 
  scale_y_continuous(limits = c(-4, 5)) +
  theme(aspect.ratio = 1)

p1
```
image

Since the locations are already worked out by this time, I think we can safely remove non-printed characters from the data frame returned by `measure_text`. The following from my next commit:

```
p1
```
image

**Comment by teunbrand** [comment]
Yes that seems a sensible decision. I tried to determine if the newlines contributed to the text width, but they don't (even though they are given a width in the data).

**Comment by teunbrand** [comment]
You know what, I think I understood what I was doing, but after trying to make some explanatory illustrations, it turned out I do not understand how the bisector method works (or it works differently to how I thought). It was roughly based on [this SO question](https://stackoverflow.com/questions/54033808/how-to-offset-polygon-edges) while also looking at [this question](https://stackoverflow.com/a/68109283/11374827), but somehow I couldn't get the thing to work in R out of the box, so I kept trial-and-error'ing my way through until I ended up with something that worked.

**Comment by AllanCameron** [comment]
I sat down with pencil and paper (and ruler!) to get my head round it, and think I've managed to simplify the bisector method. The offset distance should just be `cos(bisector angle - segment angle) * d`, so the bisector function has simplified to
```r
.get_offset <- function(x, y, d = 0) {

  theta <- .angle_from_xy(x, y, norm = TRUE)

  theta_bisect <- (.before(theta) + .after(theta)) / 2

  offset <- outer(cos(theta_bisect - .after(theta)), d)

  # Project new points at the bisector
  xout <- offset * cos(theta_bisect) + x
  yout <- offset * sin(theta_bisect) + y

  # Calculate arc length
  arc_length <- sapply(seq(ncol(xout)), function(i) {
     .arclength_from_xy(xout[,i], yout[,i])
  })

  return(list(x = xout, y = yout, arc_length = arc_length))
}
```
Have a look at this and make sure it does what you expect.

**Comment by teunbrand** [comment]
Hey Allan,

I doesn't quite do the thing I'd have liked it to do. The angles seem too short in around the middle point in the reprex below. Below, I use the new function (with the rest of my current branch):

``` r
devtools::load_all("~/packages/geomtextpath/")
#> i Loading geomtextpath
#> Loading required package: ggplot2
#> Warning: package 'ggplot2' was built under R version 4.1.1
#> Warning: package 'testthat' was built under R version 4.1.1

.get_offset <- function(x, y, d = 0) {
  
  theta <- .angle_from_xy(x, y, norm = TRUE)
  
  theta_bisect <- (.before(theta) + .after(theta)) / 2
  
  offset <- outer(cos(theta_bisect - .after(theta)), d)
  
  # Project new points at the bisector
  xout <- offset * cos(theta_bisect) + x
  yout <- offset * sin(theta_bisect) + y
  
  # Calculate arc length
  arc_length <- sapply(seq(ncol(xout)), function(i) {
    .arclength_from_xy(xout[,i], yout[,i])
  })
  
  return(list(x = xout, y = yout, arc_length = arc_length))
}


x <- c(1:5)
y <- c(1,2,3,2,1)

oset <- .get_offset(x, y, d = 1)

plot(x, y, type = "b", xlim = range(x, oset$x), ylim = range(y, oset$y))
lines(oset$x[,1], oset$y[,1], col = 2)
```



``` r
sqrt((oset$x[, 1] - x)^2 + (oset$y[,1] -y)^2)
#> [1] 1.0000000 1.0000000 0.7071068 1.0000000 1.0000000
```

<sup>Created on 2021-11-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Whereas if I do not use the new function:

``` r
devtools::load_all("~/packages/geomtextpath/")
#> i Loading geomtextpath
#> Loading required package: ggplot2
#> Warning: package 'ggplot2' was built under R version 4.1.1
#> Warning: package 'testthat' was built under R version 4.1.1

x <- c(1:5)
y <- c(1,2,3,2,1)

oset <- .get_offset(x, y, d = 1)

plot(x, y, type = "b", xlim = range(x, oset$x), ylim = range(y, oset$y))
lines(oset$x[,1], oset$y[,1], col = 2)
```



``` r
sqrt((oset$x[, 1] - x)^2 + (oset$y[,1] -y)^2)
#> [1] 1.000000 1.000000 1.414214 1.000000 1.000000
```

<sup>Created on 2021-11-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by AllanCameron** [comment]
Ah, you're right. I flipped a multiplication. Can you try this?
``` r
.get_offset <- function(x, y, d = 0) {
  
  theta <- .angle_from_xy(x, y, norm = TRUE)
  
  theta_bisect <- (.before(theta) + .after(theta)) / 2
  
  offset <- outer(1/cos(theta_bisect - .before(theta)), d)
  
  # Project new points at the bisector
  xout <- offset * cos(theta_bisect) + x
  yout <- offset * sin(theta_bisect) + y
  
  # Calculate arc length
  arc_length <- sapply(seq(ncol(xout)), function(i) {
    .arclength_from_xy(xout[,i], yout[,i])
  })
  
  return(list(x = xout, y = yout, arc_length = arc_length))
}
```

**Comment by teunbrand** [comment]
Yes this seems to work perfectly! Great work, could you explain to someone as bad at maths as me why `1 / cos()` gives the right offsets? I understand that `theta_bisect - .before(theta)` is the angle between the bisector and the perpendicular on the previous linepiece, and that `outer(..., d)` multiplies by every offset.

**Comment by AllanCameron** [comment]
Here's the logic.

Start with the plot:
```r
xy <- data.frame(x = c(1:5), y = c(1,2,3,2,1))

plot(xy, type = 'b', xlim = c(0, 5), ylim = c(0, 5))
```
image

Now we draw in some line segments to show where the offsets are:
``` r
grad <- diff(xy$y) / diff(xy$x)

seg_angles <- atan(grad) + pi / 2

offset <- 1

offset_x <- offset * cos(seg_angles)

offset_y <- offset * sin(seg_angles)

offset_points_x <- offset_x[c(1, 1:4)] + xy$x
offset_points_y <- offset_y[c(1, 1:4)] + xy$y

segments(xy$x, xy$y, offset_points_x, offset_points_y, lty = 2, col = 2)
```
image

We'll add some ablines to show the offsets more clearly:
``z r
for(i in seq_along(offset_points_x))
abline(offset_points_y[i] - grad[i] * offset_points_x[i], grad[i],
       col = 4, lty = 3)
```
![image](https://user-images.githubusercontent.com/33987720/143506251-40c532fc-73e1-4302-ab8f-ee5b2542cd05.png)

Finally, let's draw the bisectors at each point:
```r
for(i in seq(nrow(xy))) {
abline(xy$y[i] - tan(bisectors)[i] * xy$x[i], tan(bisectors)[i], col = 3,
       lty = 3)
}
```
Now look at triangle ABC, and note B has to be a right angle.
``` 
text(labels = c("A", "B", "C"), x = c(2.9, 2.4, 2.9),
     y = c(3.3, 3.7, 4.1), cex = 0.8)
```
image

Also note that line AB is our offset value (d), so the hypotenuse of the triangle, which is the distance we're trying to find must be `d/cos(A)`

To help show that A is just the angle of the previous segment minus the angle of the current bisector, we'll draw a line at 0 degrees:
```r
abline(h = xy$y[3], col = 5)
```
image

If you count counterclockwise from this line, you'll see our bisector is 90 degrees and the segment line is 135 degrees, so our new distance should be `d/cos(45)` or `1/0.7071068` which is `sqrt(2)`

**Comment by teunbrand** [comment]
Amazing, well done and even I see now with that clear explanation! Seems much more intelligible than whatever I improvised :')

**Comment by AllanCameron** [comment]
I'm sure a mathematician could show that the old and new versions are equivalent, but it's good to have a simpler calculation that we can understand.

**Pull request merged**
