### PR TITLE
Labels fixes part II

### PR DESCRIPTION
**Pull request by teunbrand**
Hi Alan,

Here are a few fixes again for the labels. I've given the textbox its own linewidth, linetype and colour aesthetics, so it no longer becomes blank when `include_path = FALSE`. Also, the straight labels now get a straight path. 

In addition,
I've regenerated the logo at 300ppi instead of 3000ppi, so it is now much smaller. Also, I've removed the withr dependency without complaints from the CI or local R CMD check.

I've been trying to use text-angles for the placement of the text boxes but it does work great. If you want to experiment yourself, here is the code that I've written (but not included in the PR)

```
.curved_textbox <- function(
  path,
  text,
  label,
  padding = unit(0.25, "lines"),
  radius  = unit(0.15, "lines")
) {
  padding <- as_inch(padding)
  metrics <- attr(label, "metrics")
  height <- c(0, 1) * metrics$height + c(-1, 1) * padding

  if (nrow(text) > 1) {
    # Find left/right points
    lr <- c(which.min(text$left), which.max(text$right))

    # Get min / mid / max height
    height <- c(0, 1) * metrics$height + c(-1, 1) * padding
    hheight <- 0.5 * diff(height)
    height <- c(height[1], sum(height) / 2, height[2])

    # Apply height to minimal offset
    offset <- as_inch(attr(label, "offset"))[unique(label$y_id)]
    offset <- min(offset) + metrics$x_adj
    offset <- c(0, offset + height)

    # Calculate offsets
    offset <- .get_offset(path$x, path$y, offset)

    # Find coordinates of left/right points at mid-height
    lims <- range(text$left, text$right)
    lims <- approx_multiple(offset$arc_length[, 1], lims,
                            cbind(offset$x[, 3], offset$y[, 3], offset$arc_length[, 3]))

    # From mid-height point, extend half-height to top/bottom
    ang <- text$angle[lr] * .deg2rad
    ang <- c(ang + .halfpi, ang - .halfpi)
    xx <- cos(ang) * hheight + lims[, 1]
    yy <- sin(ang) * hheight + lims[, 2]

    # At top/bottom, add padding
    ang <- text$angle[lr] * .deg2rad
    ang <- ang + c(1, 0, 1, 0) * pi
    x <- cos(ang) * padding + xx
    y <- sin(ang) * padding + yy

    # Check which points fall between corners
    keep  <- offset$arc_length[, 3] > lims[1, 3] & offset$arc_length[, 3] < lims[2, 3]
    nkeep <- sum(keep)

    # Add points in-between corners
    # Note: points are left-right-left-right so we'll reorder
    x <- c(x[3], offset$x[keep, 2], x[c(4, 2)], rev(offset$x[keep, 4]), x[1])
    y <- c(y[3], offset$y[keep, 2], y[c(4, 2)], rev(offset$y[keep, 4]), y[1])

  } else {
    # Simple rotation of a rectangle
    xx <- (metrics$width  * c(-0.5, 0.5) + c(-padding, padding))[c(1, 2, 2, 1)]
    yy <- (diff(height)   * c(-0.5, 0.5))[c(1, 1, 2, 2)]
    rot <- text$angle * .deg2rad
    x <- xx * cos(rot) - yy * sin(rot) + text$x
    y <- xx * sin(rot) + yy * cos(rot) + text$y
    nkeep <- 0
  }

  radius <- as_inch(radius)
  if (radius > 0.01) {
    if (radius > 0.5 * diff(range(height))) {
      radius  <- 0.5 * diff(range(height))
    }
    # Make closed polygon by inserting midpoint between start and end
    n <- length(x)
    x_start <- (x[1] + x[n]) / 2
    y_start <- (y[1] + y[n]) / 2
    x <- c(x_start, x, x_start)
    y <- c(y_start, y, y_start)

    # Round corners
    corners <- c(2, 3 + nkeep, 4 + nkeep, 5 + 2 * nkeep)
    xy <- .round_corners(x, y, radius, at = corners)
    x <- xy$x
    y <- xy$y
  }
  return(data_frame(x = x, y = y, id = text$id[1]))
}
```

### CODE REVIEW

**Comment by AllanCameron** [comment]
Great work Teun. 

I do worry slightly that we're turning the textpath grob into a "one grob to rule them all" with so many parameters to handle. Do you think the textpath labels are going to be useful enough to warrant all the trouble? I can foresee a few uses (particularly labels in polar co-ordinates), but one of the advantages of the textpaths is that you can avoid much of the overplotting that make labels necessary. They would be a nice addition if we can make them work in most cases, and I'm sure we could get them to work if we put the effort in (as you already have), You know the remaining challenges better than I do - do you think this is something we should definitely pursue?

**Comment by teunbrand** [comment]
Yes I share that worry, there has been a creep of additional parameters since the moment we've got the essence working. The textboxed variants works well enough in most cases to be useful in my opinion, but I don't use `geom_label()` a lot either. I may have given the wrong impression in my first PR that this is all a mess, but I've neglected to show that they mostly work as you'd expect.

I think eventually we'd have to divorce the textboxed variant from the text-only variant to solve a specific issue, which I tried to have kept in mind when integrating it (there are just two blocks of code to remove from the `makeContent` method). To do this however, we'd have to refactor a bit of code such that it is easier to reuse in e.g. a `labelpathGrob()` function/method and we can have a think if we'd want to divorce specific settings as well for which we have some separate code paths (for example straight text).

**Comment by AllanCameron** [comment]
I know they work mostly as expected, and the straight labels seem to work pretty well. The curved labels do look good in some situations. I think separating them into different grobs makes sense though.

I've been having a play with some practical applications of the package, and it occurs to me that in _most_ circumstances people would want the ability to produce curved text that directly label some noisy or geometric lines. I know we have discussed this before and that there is always the option of adding a smoothed textpath without a line (as I have demonstrated in the readme), but it seems to me that this would be such a common application that we should include a mechanism to auto-smooth text. For example, I really struggled to find any motivating real-world example for the use of `geom_textline` using built-in data sets, but this would have been very easy (fun, even) if there was a smoothing option. I have a feeling that this would greatly help the appearance of the labelpath in many instances too.

**Comment by teunbrand** [comment]
Am I understanding correctly that you'd want the path to be as-is, but the text smoothened? If so, why don't we set the default `include_line = FALSE` for the `geom_textsmooth()` function? It's easy enough to use `geom_path() + geom_textsmooth()` together. I'm not exactly sure where what you're suggesting differs from the options already available or couldn't be solved through a stat that smooths the data in a particular way.

>  I really struggled to find any motivating real-world example for the use of geom_textline using built-in data sets

The `pressure` dataset seems suitable for this purpose.

``` r
library(geomtextpath)
#> Loading required package: ggplot2
#> Warning: package 'ggplot2' was built under R version 4.1.1

ggplot(pressure, aes(temperature, pressure)) +
  geom_textline(label = "Under pressure", size = 8, vjust = -0.5)
```



<sup>Created on 2021-12-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by AllanCameron** [comment]
A like the pressure example! We should use this instead of the existing one in the readme.

You are understanding me correctly about the line being as it is but the text being smoothed. You are also right that what I am suggesting could already be solved through existing tools. It just seems such a common use case that using two geoms with particular settings seems a bit of a cumbersome work-around.

**Pull request merged**
