### PR TITLE
Guide axis textpath

### PR DESCRIPTION
**Pull request by teunbrand**
Hi Allan,

I think the changes in this PR are sufficient to create a new axis that is compatible with the new `coord_radial()`.
I'll leave this as a draft for now, because we might need some changes upstream in ggplot2 still, mostly the export of `GuideAxisTheta`.

Anyway, here are some examples:

``` r
devtools::load_all("~/packages/geomtextpath")
#> ℹ Loading geomtextpath
#> Loading required package: ggplot2
#> 
#> ! Adding files missing in collate:
#>   'C:/Users/Teun/Documents/packages/geomtextpath/R/guide_axis_textpath.R'

df <- data.frame(x = c("A long axis label", "Another long label",
                       "The longest label of all", "Yet another label"),
                 y = c(8, 6, 10, 4))

p <- ggplot(df, aes(x, y, fill = x)) + 
  geom_col(width = 0.5) +
  scale_fill_brewer(type = "qual") +
  theme(axis.text.x = element_text(size = 15),
        legend.position = "none",
        axis.line.x = element_line())

p + coord_radial() +
  guides(theta = guide_axis_textpath())
```

With partial polar coordinates:

``` r
p + coord_radial(start = 0.4 * pi, end = 1.6 * pi) +
  guides(theta = guide_axis_textpath())
```

As part of a stacked axis:

``` r
p + coord_radial(start = 0.4 * pi, end = 1.6 * pi) +
  guides(theta = guide_axis_stack("axis_textpath", "axis_textpath"))
```

<sup>Created on 2023-12-14 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### CODE REVIEW

**Comment by teunbrand** [comment]
Alright this is now ready to merge or review I think.
Had to bump ggplot2 version to 3.5.0 for `coord_radial()` and the new guide system.
It should now support all of the `coord_radial()` features:

``` r
devtools::load_all("~/packages/geomtextpath")
#> ℹ Loading geomtextpath
#> Loading required package: ggplot2

df <- data.frame(x = c("A long axis label", "Another long label",
                       "The longest label of all", "Yet another label"),
                 y = c(8, 6, 10, 4))

ggplot(df, aes(x, y, fill = x)) + 
  geom_col(width = 0.5) +
  coord_radial(
    inner.radius = 0.5, 
    start = 0.25 * pi, 
    end   = 1.75 * pi) +
  guides(
    theta     = "axis_textpath",
    theta.sec = "axis_textpath"
  )
```



<sup>Created on 2024-03-05 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by AllanCameron** [comment]
Thanks Teun. I need to address a couple of failing tests on CRAN before 10th March, so this is quite timely. It means we can do a minor version bump and I'll submit again (if I can remember the process)

**Comment by teunbrand** [comment]
> I need to address a couple of failing tests on CRAN before 10th March

If my memory serves me correctly, that should be covered in #108 so hopefully it wouldn't be too bad of a headache!

**Comment by teunbrand** [comment]
> (if I can remember the process)

I found out about the very handy `usethis::use_release_issue()` that posts a checklist as a github issue.

**Pull request merged**
